### ISSUE TITLE
Enhance SEO for Redot Engine Website

### ISSUE THREAD

**Issue by SerkZex** [YanLi-FE/redot-landing-page#14]
To improve our website's visibility and ranking on search engines, we need to implement SEO best practices. This will help in attracting more organic traffic and improving user engagement.

**1. Meta Tags:**
* Add appropriate meta titles and descriptions to all key pages.
* Ensure meta tags are optimized for relevant keywords.

**2. Alt Text for Images:**
* Add descriptive alt text for all images on the site.
* Ensure alt text includes relevant keywords where appropriate.

**3. _Sitemap and Robots.txt (Optional for if you deem it to early):_**
* _Create and submit a sitemap to search engines._
* _Update the [robots.txt](https://developers.google.com/search/docs/crawling-indexing/robots/intro) file to guide search engine crawlers._

**Comment by opdev1004** [comment]
+ sitemap.xml
So I think we need to add a nuxt SEO plugin.
